language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

install: "pip install -r requirements.txt"
script: nosetests
notifications:
  email: false
before_install:
  - pip install codecov
after_success:
  - codecov
