language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

install: "pip install -r requirements.txt"
notifications:
  email: false
script:
  - coverage run test_calculator.py
after_success:
  - codecov
